web:
    image: rails:4.2.1
    working_dir: /usr/src/app
    volumes:
        - $PWD/app/:/usr/src/app
    ports:
        - "3000:3000"
    links:
        - db
    command: bash run.sh
    restart: always
db:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: testtest
        MYSQL_DATABASE: big_league
        MYSQL_USER: superuser
        MYSQL_PASSWORD: abc123
    ports:
        - "3306:3306"
    restart: always
